# Adapted from https://github.com/commercialhaskell/stack
language: nix
sudo: false

env:
  - TRAVIS_NODE_VERSION="11.6.0"

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - .stack-work

install:
  - unset CC
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
  - ./.travis/install-stack.sh

script:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - GHC_OPTIONS="-Werror"
  - |
    set -ex

    # Run Haskell tests
    stack build
    set +ex
